{"success":false,"status_code":500,"error":"An error occurred","traceback":"Traceback (most recent call last):\n  File \"/home/GetLinkBackend/helpers/utils/advice.py\", line 26, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/GetLinkBackend/user_profile/views.py\", line 259, in post\n    return service_response(\n           ^^^^^^^^^^^^^^^^^\nTypeError: service_response() got an unexpected keyword argument 'succes'\n"}