{"success":false,"status_code":500,"error":"An error occurred","traceback":"Traceback (most recent call last):\n  File \"/home/GetLinkBackend/venv/lib/python3.12/site-packages/rest_framework/parsers.py\", line 66, in parse\n    return json.load(decoded_stream, parse_constant=parse_constant)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/GetLinkBackend/venv/lib/python3.12/site-packages/rest_framework/utils/json.py\", line 31, in load\n    return json.load(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/json/__init__.py\", line 293, in load\n    return loads(fp.read(),\n           ^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/json/__init__.py\", line 359, in loads\n    return cls(**kw).decode(s)\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 26 column 1 (char 30)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/GetLinkBackend/helpers/utils/advice.py\", line 30, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/GetLinkBackend/assessment/views.py\", line 1885, in post\n    serializer = EmailInviteSerializer(data=request.data)\n                                            ^^^^^^^^^^^^\n  File \"/home/GetLinkBackend/venv/lib/python3.12/site-packages/rest_framework/request.py\", line 220, in data\n    self._load_data_and_files()\n  File \"/home/GetLinkBackend/venv/lib/python3.12/site-packages/rest_framework/request.py\", line 283, in _load_data_and_files\n    self._data, self._files = self._parse()\n                              ^^^^^^^^^^^^^\n  File \"/home/GetLinkBackend/venv/lib/python3.12/site-packages/rest_framework/request.py\", line 358, in _parse\n    parsed = parser.parse(stream, media_type, self.parser_context)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/GetLinkBackend/venv/lib/python3.12/site-packages/rest_framework/parsers.py\", line 68, in parse\n    raise ParseError('JSON parse error - %s' % str(exc))\nrest_framework.exceptions.ParseError: JSON parse error - Expecting value: line 26 column 1 (char 30)\n"}